name: test pessoa

on: será executado em cada push

jobs:
  build: windows

    runs-on: 

    steps: 
    - uses: actions/checkout@v2
    
    - name: Setup Python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.2'

    - name: Run test 
      run: python -m unittest discover -s .